server:
  port: 8000
spring:
  application:
    name: zuul
##
zuul:
  routes:
    order:
      path: /order/**
      serverId: order
  retryable: true
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

  
ribbon:
  ConnectTimeout: 250 # 连接超时时间(ms)
  ReadTimeout: 2000 # 通信超时时间(ms)
  OkToRetryOnAllOperations: true # 是否对所有操作重试
  MaxAutoRetriesNextServer: 2 # 同一服务不同实例的重试次数
  MaxAutoRetries: 1 # 同一实例的重试次数
