server:
  port: 8000
spring:
  application:
    name: zuul
##
zuul:
  routes:
    order:
      path: /order/**
      serverId: order
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
